### ISSUE TITLE
Allow DNS example should limit to kube-dns

### ISSUE THREAD

**Issue by jpds** [ahmetb/kubernetes-network-policy-recipes#34]
The Allow DNS example here:

- https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/11-deny-egress-traffic-from-an-application.md#allowing-dns-traffic

Should have limits in place for `kube-dns` traffic,

**Comment by jpds** [comment]
Needs:

```
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
```

Not sure how to combine with `namespaceSelector`.

**Comment by ahmetb** [comment]
We did port 53 because "choosing a specific set of pods from another namespace" was not available back in the day.

Now it's available but it still isn't available on _most_ Kubernetes network plugins (it's like available in only the latest version of Calico).

This is explained in https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md.

We probably should not update page 11-* until most plugins start supporting this feature.

**Comment by boredabdel** [comment]
I had this in a production setup before. There are two main challenges with Network Policies and kube-dns

- kube-dns runs in the kube-system namespaces, which by default doesn't have labels (the namespace itself) (labels are needed for for the nameSpaceSelector).
- We cannot assume that it's always going to be kube-dns, in some implementations other DNS systems are used like coreDNS.

So i think the example as is, is good enough for now.
